trigger:
- master
pool:
 vmImage: 'ubuntu-latest'
variables:
 buildConfiguration: 'Release'
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: '$(kirankvathan)/$(netapp)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/charts'
    ArtifactName: 'charts'
    publishLocation: 'Container'
